
sudo: require
language: cpp
compiler: gcc

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y ppa:deadsnakes/ppa
  - sudo apt-get update

install:
  - sudo apt-get install software-properties-common
  - sudo apt-get install -qq g++-7
  - sudo apt-get install python3.6
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-7 90
  - sudo apt-get update -qq
  - npm install markdownlint-cli markdown-spellcheck

script: 
  - ./build.sh
  - ./travis_qmake_gcc_cpp11_gcov
  - python3 ./fix_coverage.py main.gcno main.gcno.out
  - mv main.gcno.out main.gcno
  - ./get_code_cov.sh
  - ./node_modules/.bin/mdspell -n -a -r -x --en-us '**/*.md' '!**/node_modules/**/*.md'
  - ./node_modules/.bin/markdownlint -i ./node_modules -i ./include -i ./lib '**/*.md'

after_success: 
  - bash <(curl -s https://codecov.io/bash)
